-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Bill"
(
    amount money NOT NULL,
    date date NOT NULL,
    current_season date NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Employee"
(
    "ID" integer NOT NULL,
    employee_type text COLLATE pg_catalog."default",
    name name COLLATE pg_catalog."C",
    address text COLLATE pg_catalog."default",
    phone integer,
    email name COLLATE pg_catalog."C",
    hire_date integer,
    salary integer,
    department name COLLATE pg_catalog."C",
    supervisor name COLLATE pg_catalog."C",
    CONSTRAINT "Employee_pkey" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE pgsql
);

CREATE TABLE IF NOT EXISTS public."Guest"
(
    "ID" integer NOT NULL,
    identification_type name COLLATE pg_catalog."C",
    identification_number integer,
    address name COLLATE pg_catalog."C",
    home_phone integer,
    mobile_phone integer,
    CONSTRAINT "Guest_pkey" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE pgsql
);

CREATE TABLE IF NOT EXISTS public."Guest_Category"
(
    price money NOT NULL,
    discount text[] COLLATE pg_catalog."default" NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Hotel"
(
    "ID" integer NOT NULL,
    name name COLLATE pg_catalog."C" NOT NULL,
    address text[] COLLATE pg_catalog."default" NOT NULL,
    phone_number integer NOT NULL,
    feature text[] COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Hotel_pkey" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE pgsql
);

CREATE TABLE IF NOT EXISTS public."Reservation"
(
    "ID" integer NOT NULL,
    check_in_date date NOT NULL,
    check_out_date date NOT NULL,
    CONSTRAINT "Reservation_pkey" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE pgsql
);

CREATE TABLE IF NOT EXISTS public."Review"
(
    "Review_ID" integer NOT NULL,
    date date,
    public_display_name name COLLATE pg_catalog."C",
    text text COLLATE pg_catalog."default",
    score integer,
    CONSTRAINT "Review_pkey" PRIMARY KEY ("Review_ID")
        USING INDEX TABLESPACE pgsql
);

CREATE TABLE IF NOT EXISTS public."Room"
(
    price integer,
    size integer
);

CREATE TABLE IF NOT EXISTS public."Room_Type"
(
    room_type_id name COLLATE pg_catalog."C" NOT NULL,
    price money,
    size integer,
    capacity integer,
    features text COLLATE pg_catalog."default",
    CONSTRAINT "Room_Type_pkey" PRIMARY KEY (room_type_id)
        USING INDEX TABLESPACE pgsql
);

CREATE TABLE IF NOT EXISTS public."Season"
(
    "season_ID" integer NOT NULL,
    name name COLLATE pg_catalog."C" NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    CONSTRAINT "Season_pkey" PRIMARY KEY ("season_ID")
        USING INDEX TABLESPACE pgsql
);

CREATE TABLE IF NOT EXISTS public."Services"
(
    "ID" integer NOT NULL,
    price money NOT NULL,
    service_type text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Services_pkey" PRIMARY KEY ("ID")
        USING INDEX TABLESPACE pgsql
);

CREATE TABLE IF NOT EXISTS public."Hotel_Reservation"
(
    "Hotel_ID" integer NOT NULL,
    "Reservation_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Hotel_Season"
(
    "Hotel_ID" integer NOT NULL,
    "Season_season_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Reservation_Bill"
(
    "Reservation_ID" integer NOT NULL,
    "Bill_date" date NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Reservation_Guest"
(
    "Reservation_ID" integer NOT NULL,
    "Guest_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Hotel_Employee"
(
    "Hotel_ID" integer NOT NULL,
    "Employee_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Guest_Category_Guest"
(
    "Guest_Category_discount" text[] COLLATE pg_catalog."default" NOT NULL,
    "Guest_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Services_Bill"
(
    "Services_ID" integer NOT NULL,
    "Bill_amount" money NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Services_Hotel"
(
    "Services_ID" integer NOT NULL,
    "Hotel_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Guest_Review"
(
    "Guest_ID" integer NOT NULL,
    "Review_Review_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Room_Type_Employee"
(
    "Room_Type_room_type_id" name COLLATE pg_catalog."C" NOT NULL,
    "Employee_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Room_Type_Guest"
(
    "Room_Type_room_type_id" name COLLATE pg_catalog."C" NOT NULL,
    "Guest_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Room_Type_Hotel"
(
    "Room_Type_room_type_id" name COLLATE pg_catalog."C" NOT NULL,
    "Hotel_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Room_Type_Reservation"
(
    "Room_Type_room_type_id" name COLLATE pg_catalog."C" NOT NULL,
    "Reservation_ID" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Room_Room_Type"
(
    "Room_price" integer,
    "Room_Type_room_type_id" name COLLATE pg_catalog."C" NOT NULL
);

CREATE TABLE IF NOT EXISTS public."Review_Hotel"
(
    "Review_Review_ID" integer NOT NULL,
    "Hotel_ID" integer NOT NULL
);

ALTER TABLE IF EXISTS public."Guest_Category"
    ADD FOREIGN KEY (price)
    REFERENCES public."Bill" (amount) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Hotel_Reservation"
    ADD FOREIGN KEY ("Hotel_ID")
    REFERENCES public."Hotel" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Hotel_Reservation"
    ADD FOREIGN KEY ("Reservation_ID")
    REFERENCES public."Reservation" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Hotel_Season"
    ADD FOREIGN KEY ("Hotel_ID")
    REFERENCES public."Hotel" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Hotel_Season"
    ADD FOREIGN KEY ("Season_season_ID")
    REFERENCES public."Season" ("season_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Reservation_Bill"
    ADD FOREIGN KEY ("Reservation_ID")
    REFERENCES public."Reservation" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Reservation_Bill"
    ADD FOREIGN KEY ("Bill_date")
    REFERENCES public."Bill" (date) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Reservation_Guest"
    ADD FOREIGN KEY ("Reservation_ID")
    REFERENCES public."Reservation" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Reservation_Guest"
    ADD FOREIGN KEY ("Guest_ID")
    REFERENCES public."Guest" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Hotel_Employee"
    ADD FOREIGN KEY ("Hotel_ID")
    REFERENCES public."Hotel" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Hotel_Employee"
    ADD FOREIGN KEY ("Employee_ID")
    REFERENCES public."Employee" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Guest_Category_Guest"
    ADD FOREIGN KEY ("Guest_Category_discount")
    REFERENCES public."Guest_Category" (discount) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Guest_Category_Guest"
    ADD FOREIGN KEY ("Guest_ID")
    REFERENCES public."Guest" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Services_Bill"
    ADD FOREIGN KEY ("Services_ID")
    REFERENCES public."Services" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Services_Bill"
    ADD FOREIGN KEY ("Bill_amount")
    REFERENCES public."Bill" (amount) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Services_Hotel"
    ADD FOREIGN KEY ("Services_ID")
    REFERENCES public."Services" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Services_Hotel"
    ADD FOREIGN KEY ("Hotel_ID")
    REFERENCES public."Hotel" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Guest_Review"
    ADD FOREIGN KEY ("Guest_ID")
    REFERENCES public."Guest" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Guest_Review"
    ADD FOREIGN KEY ("Review_Review_ID")
    REFERENCES public."Review" ("Review_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Room_Type_Employee"
    ADD FOREIGN KEY ("Room_Type_room_type_id")
    REFERENCES public."Room_Type" (room_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Room_Type_Employee"
    ADD FOREIGN KEY ("Employee_ID")
    REFERENCES public."Employee" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Room_Type_Guest"
    ADD FOREIGN KEY ("Room_Type_room_type_id")
    REFERENCES public."Room_Type" (room_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Room_Type_Guest"
    ADD FOREIGN KEY ("Guest_ID")
    REFERENCES public."Guest" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Room_Type_Hotel"
    ADD FOREIGN KEY ("Room_Type_room_type_id")
    REFERENCES public."Room_Type" (room_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Room_Type_Hotel"
    ADD FOREIGN KEY ("Hotel_ID")
    REFERENCES public."Hotel" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Room_Type_Reservation"
    ADD FOREIGN KEY ("Room_Type_room_type_id")
    REFERENCES public."Room_Type" (room_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Room_Type_Reservation"
    ADD FOREIGN KEY ("Reservation_ID")
    REFERENCES public."Reservation" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Room_Room_Type"
    ADD FOREIGN KEY ("Room_price")
    REFERENCES public."Room" (price) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Room_Room_Type"
    ADD FOREIGN KEY ("Room_Type_room_type_id")
    REFERENCES public."Room_Type" (room_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Review_Hotel"
    ADD FOREIGN KEY ("Review_Review_ID")
    REFERENCES public."Review" ("Review_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Review_Hotel"
    ADD FOREIGN KEY ("Hotel_ID")
    REFERENCES public."Hotel" ("ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;